"""迁移脚本

Revision ID: ec9306723e7d
Revises: 
Create Date: 2026-01-24 07:52:52.207102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec9306723e7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.create_foreign_key(None, 'app_ai_mcp', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'app_ai_mcp', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'app_job', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'app_job', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'app_job_log', 'app_job', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'app_myapp', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'app_myapp', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'gen_demo', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'gen_demo', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'gen_table', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'gen_table', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否主键',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('true'),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text('false'),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.create_foreign_key(None, 'gen_table_column', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'gen_table_column', 'gen_table', ['table_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'gen_table_column', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_dept', 'sys_dept', ['parent_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_dict_data', 'sys_dict_type', ['dict_type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sys_log', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_log', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_menu', 'sys_menu', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_notice', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_notice', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_position', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_position', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_role_depts', 'sys_role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sys_role_depts', 'sys_dept', ['dept_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sys_role_menus', 'sys_menu', ['menu_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sys_role_menus', 'sys_role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sys_user', 'sys_user', ['created_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_user', 'sys_dept', ['dept_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_user', 'sys_user', ['updated_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'sys_user_positions', 'sys_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sys_user_positions', 'sys_position', ['position_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sys_user_roles', 'sys_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'sys_user_roles', 'sys_role', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sys_user_roles', type_='foreignkey')
    op.drop_constraint(None, 'sys_user_roles', type_='foreignkey')
    op.drop_constraint(None, 'sys_user_positions', type_='foreignkey')
    op.drop_constraint(None, 'sys_user_positions', type_='foreignkey')
    op.drop_constraint(None, 'sys_user', type_='foreignkey')
    op.drop_constraint(None, 'sys_user', type_='foreignkey')
    op.drop_constraint(None, 'sys_user', type_='foreignkey')
    op.drop_constraint(None, 'sys_role_menus', type_='foreignkey')
    op.drop_constraint(None, 'sys_role_menus', type_='foreignkey')
    op.drop_constraint(None, 'sys_role_depts', type_='foreignkey')
    op.drop_constraint(None, 'sys_role_depts', type_='foreignkey')
    op.drop_constraint(None, 'sys_position', type_='foreignkey')
    op.drop_constraint(None, 'sys_position', type_='foreignkey')
    op.drop_constraint(None, 'sys_notice', type_='foreignkey')
    op.drop_constraint(None, 'sys_notice', type_='foreignkey')
    op.drop_constraint(None, 'sys_menu', type_='foreignkey')
    op.drop_constraint(None, 'sys_log', type_='foreignkey')
    op.drop_constraint(None, 'sys_log', type_='foreignkey')
    op.drop_constraint(None, 'sys_dict_data', type_='foreignkey')
    op.drop_constraint(None, 'sys_dept', type_='foreignkey')
    op.drop_constraint(None, 'gen_table_column', type_='foreignkey')
    op.drop_constraint(None, 'gen_table_column', type_='foreignkey')
    op.drop_constraint(None, 'gen_table_column', type_='foreignkey')
    op.alter_column('gen_table_column', 'is_query',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否查询字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_list',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否列表字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_edit',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否编辑字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_insert',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否为新增字段',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_unique',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否唯一',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_nullable',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_comment='是否允许为空',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_increment',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否自增',
               existing_nullable=False)
    op.alter_column('gen_table_column', 'is_pk',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='是否主键',
               existing_nullable=False)
    op.drop_constraint(None, 'gen_table', type_='foreignkey')
    op.drop_constraint(None, 'gen_table', type_='foreignkey')
    op.drop_constraint(None, 'gen_demo', type_='foreignkey')
    op.drop_constraint(None, 'gen_demo', type_='foreignkey')
    op.drop_constraint(None, 'app_myapp', type_='foreignkey')
    op.drop_constraint(None, 'app_myapp', type_='foreignkey')
    op.drop_constraint(None, 'app_job_log', type_='foreignkey')
    op.drop_constraint(None, 'app_job', type_='foreignkey')
    op.drop_constraint(None, 'app_job', type_='foreignkey')
    op.drop_constraint(None, 'app_ai_mcp', type_='foreignkey')
    op.drop_constraint(None, 'app_ai_mcp', type_='foreignkey')
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
